### ISSUE TITLE
a PDF of the paper

### ISSUE THREAD

**Issue by Nnboy** [Ssz990220/GC_DualRobot#1]
老哥打扰一下，想问下咱的论文上网了吗？我没有查到😂

**Comment by Ssz990220** [comment]
文章还在送审，暂时没有发表在Archive上。
正式发表之后会在这里附上链接，烦请耐心等待一下，近期会做更新。

**Comment by Ssz990220** [comment]
Hi,

The paper has been accepted and will be published. The pre-print version can be accessed through [this link](https://www.researchgate.net/publication/372782966_Solving_the_AXBYCZ_Problem_for_a_Dual-Robot_System_with_Geometric_Calculus).

The link will be updated and attached to the README after final publication.

Thanks for your consideration and appreciation.

Best
